server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123

social:
  qq:
    appId: xxx
    appSecret: yyy
    filterProcessesUrl: /qqLogin
    providerId: callback.do
    signupUrl: /signup
  weixin:
    appId: wxd99431bbff8305a0
    appSecret: 60f78681d063590a469f1b297feff3c4
